#+MACRO: term  @@html:<q class="term">@@$1@@html:</q>@@
#+MACRO: logic @@html:<span class="logic">@@$1@@html:</span>@@
#+MACRO: var   @@html:<var>@@$1@@html:</var>@@
#+MACRO: dfn   @@html:<dfn>@@$1@@html:</dfn>@@
#+HTML_HEAD: <meta charset="utf-8"/><style>pre { font-size: 14px; } body {max-width: 32em; font-size: 19px; font-family: Palatino, 'Palatino Linotype', 'Palatino LT STD', 'Book Antiqua', Georgia, serif; } li p:last-of-type {margin-bottom: 0px; } dfn { color: green; font-style: italic; } q.term { quotes: "«" "»"; font-family: monospace; font-size: 90%; }</style>
#+OPTIONS:   H:6 num:nil toc:2

* Categories

** Section I
#+INCLUDE: "aristotle-categories-1-2.org"
*** 3. Concerning Predicates
- Aristotle argues that {{{term(predicable)}}} is a transitive relation.
- *Definition.* A {{{term(species)}}} (Gk: εἶδος, /eidos/) is a set or a class
  of "things".
  - /Remark/. The word /eidos/ coincidentally is Plato's term for "Form".
  - /Caution:/ *do not* confuse this term with the modern use of the
    term "species", which appears in biology and (oddly enough)
    mathematics. They are completely unrelated to Aristotle's
    {{{term(species)}}}.
- *Puzzle.* How do we /specify/ a species?
- Aristotle provides a framework for "intensional definitions" of the
  form "A [species] is a [genus] such that [differentiae]". Species then
  have a hierarchical structure, like a tree. That is, we should think
  of {{{term(genus)}}} as an underlying species which we refine using
  predicates or {{{term(differentiae)}}}. The
  {{{term(differentiae)}}} is not {{{term(present in)}}} a subject,
  Aristotle tells us in chapter 5 (3a21).
- *Caution/Danger:* I may be blurring lines here, supposing that a 
  {{{term(genus)}}}
  /is/ a {{{term(species)}}}.
  It may be the case that I am in error here, but no one
  appears to discuss this anywhere. If we were programming this up in,
  say, haskell, I would probably attempt something like the following:
  
  #+BEGIN_SRC haskell
  species :: * --- species is a type
  predicate :: thing -> boolean

  definition :: species -> [predicates] -> species
  definition genus differentiae = ... 
  #+END_SRC
- If we have two {{{term(species)}}}, say animal and human, then what is
  predicable of animal is also predicable of human /because/ of this
  tree-like structure relating them.


*** 4. The Eight Categories of the Objects of Thought
- Aristotle asserts "of things said without any combination", i.e.,
  subjects, each "signifies" one of ten categories:
  1. Substance (e.g., man, horse)
  2. Quantity (e.g., four-foot, five-foot)
  3. Qualification (e.g., white, grammatical)
  4. Relative (e.g., double, half, larger)
  5. Where or place (e.g., in the school, in the market)
  6. When or time (e.g., yesterday, last year)
  7. Being-in-position (e.g., is-lying, is-sitting)
  8. Having or state (e.g., has-shoes-on, has-armor-on)
  9. Doing or action (e.g., cutting, burning)
  10. Being-affected (e.g., being-cut, being-burned)
- What's the deal? Why are there 10 categories when there are 8
  categories of the object of thought? Well, it turns out that
  being-in-position and state are not objects of thought. (See
  Aristotle's /Metaphysics/ 5.7.1017a7-b9)
- We can form "affirmations" by combining two "things said" together,
  e.g. "man" and "white" produces the affirmation "man is white".
  So this sketches out how to assemble a proposition, which Aristotle
  will approach in /On Interpretations/: we build it out of "things
  said", which we can better understand using categories. But first,
  lets digress on a few remarks about the translation.
**** Remarks on Translation
- These notes are taken from Ackrill's notes on his translation. I
  myself can neither read nor speak Greek (but I can write the
  alphabet!)...so I cannot independently verify Ackrill's comments,
  aside from using Google translate and Wiktionary to see what happens.
- *Substance.*
  The Greek word is the noiun from the verb "to be". So "being" or
  "entity" would be a literal equivalent. But "substance" has been
  grandfathered into this particular Aristotlian category.
- *Quantity.*
  The Greek word serves as both an interrogative and as an indefinite
  adjective (Latin, /quantum/). Only twice does Aristotle use the
  abstract noun for quantity, neither times occurs in the /Categories/.
  Instead, this translates to the interrogative adjective.
- *Qualification.*
  As an abstract noun, 'quality' is used in chapter 8 and distinguishes
  between qualities and things qualified. But as an
  interrogative adjective, 'qualification' or 'qualified' is used.
*** 5. Substance
**** (1) Primary and Secondary Substance
- Aristotle distinguishes between {{{term(Primary Substance)}}} which is
  the individual thing in question (e.g., Socrates, or any other
  individual man, etc.) and a {{{term(Secondary Substance)}}}.
- *Definition.*
  The criteria given is that a {{{dfn(primary substance)}}} is *neither*
  {{{term(predicable of)}}}
  *nor* {{{term(present in)}}} anything.
  
  It is tempting but anachronistic
  to think of this as the thing-in-itself, to borrow a Kantian phrase.
- *Definition.* The {{{dfn(secondary substance)}}}
  is {{{term(predicable of)}}} but
  not {{{term(present in)}}}...i.e.,
  {{{term(secondary substance)}}} is the species and genera of
  {{{term(substances)}}} in general.
  - Note Aristotle defines a {{{term(secondary substance)}}} as either
    the species of a (primary) {{{term(substance)}}}, or the genera
    of a species. It's not until later he notes a substances is never
    {{{term(present-in)}}} a subject (3a7), and largely implies is
    {{{term(predicable of)}}} of a subject. Since this is the more useful
    criteria, I adopt it as the definition of a secondary substance.
**** (2) Difference in the relation subsisting between essential and accidental attributes and their subject
- Aristotle argues that, given a subject, both a name and its definition
  are {{{term(predicable)}}} of the subject.
  - For this to make sense, we should note ancient Greek doesn't have
    indefinite articles. So "Socrates is human" would be a literal
    translation of "Socrates is a human", and "human is animal" would be
    "A human is an animal" in modern English. This presumably explains
    what Aristotle intended with "A name is predicable of a subject".
- For things {{{term(present in)}}} a subject, seldom will their name or
  their definition be {{{term(predicable)}}} of the subject. For
  example, "Callias is generous" but generosity is not Callias.
**** (3) All which is not primary substance is either an essential or accidental attribute of primary substance
- The fundamental point Aristotle is driving at appears to be: without
  "things" ({{{term(primary substances)}}}), there could be no
  "universals" ({{{term(secondary substances)}}}).
- "If primary substances did not exist, it would be impossible for any
  of the other things to exist."
  
  Which I read as stating, the secondary substances &
  non-substance categories only exist because primary
  substances manifest (generate?) them.
- It follows Aristotle's claim "All other things are either said of the
  primary substances as subjects or in them as subjects"
  - I read this as stating: 
    {{{logic(for all)}}} {{{var(x)}}}, ({{{logic(not)}}} {{{logic(isPrimarySubstance)}}}({{{var(x)}}}))
    {{{logic(implies)}}} [{{{logic(exists)}}} {{{var(y)}}}, {{{logic(isPrimarySubstance)}}}({{{var(y)}}}) {{{logic(and)}}} ({{{var(x)}}} {{{term(said-of)}}} {{{var(y)}}}, {{{logic(or)}}} {{{var(x)}}} {{{term(present-in)}}} {{{var(y)}}})]
    where {{{logic(isPrimarySubstance(-))}}} is the predicate testing
    if a term is a primary substance or not, and
    {{{term(present-in)}}} and {{{term(said-of)}}} are the binary
    relations we introduced in chapter 2. Or, if you like the 
    more traditional formalization presentation:
    
    ∀{{{var(x)}}} ([!P({{{var(x)}}})] ⇒ ∃{{{var(y)}}} [P({{{var(y)}}}) & (said({{{var(x)}}}, {{{var(y)}}}) {{{logic(or)}}} in({{{var(x)}}}, {{{var(y)}}}))])

  - Observe this is the contrapositive of the definition of a primary substance.
- Aristotle gives an additional justification for this claim,
  "the primary substances are subjects for all the other
  things—" aha! "—and all the other things are predicated
  of them or are in them, [because of this] that they are
  called substances most of all." (2b15)
**** (5) All species (which aren't genera) are substance in the same degree
#+BEGIN_QUOTE
...it is no more apt to say of the individual man that he is
a man than to say of the individual horse that it is a horse. And similarly of the
primary substances one is no more a substance than another... (2b23-2b28)
#+END_QUOTE
**** (6) Nothing except species and genera is secondary substance
- Aristotle asserts: "After primary substances, their species and genera 
  should be the only other things called secondary substances. For only they,
  of things predicated, reveal the primary substances." (2b29)
**** (7) Relation of primary substance to secondary substance to all other predicates is same as that of secondary substance to all other predicates
#+BEGIN_QUOTE
Further, it is because the primary substances are subjects for everything else that
they are called substances most strictly. But as the primary substances stand to
everything else, so the species and genera of the primary substances stand to all
the rest: all the rest are predicated of these. For if you will call the individual
man grammatical, then you will call both a man and an animal grammatical; and
similarly in other cases. (3a1)
#+END_QUOTE
**** (8) Substance is never accidental attribute
- Phrased differently, "No substance is in a subject".
  - Cheater's proof: By cases.
    - Case 1: This is true by definition of a primary substance.
    - Case 2: For secondary substances, "This is obvious". QED.
  - Formally, the claim is: 
    ∀{{{var(x)}}} [isSubstance({{{var(x)}}}) ⇒ ¬(∃{{{var(y)}}}, {{{logic(in)}}}({{{var(x)}}}, {{{var(y)}}}))]
  - The honest proof (i.e., the one that works) is by contrapositive.
**** (9) Differentiae of species aren't accidental attributes

**** (10) Species, genus, differentiae (as predicates) are univocal with their subject
**** (11) Primary substance is individual, secondary substance is the qualification of that which is individual
**** (12) No substance has a contrary
**** (13) No substance can be what is in varying degrees
**** (14) The particular mark of substance is that contrary qualities can be predicated of it
**** (15) Contrary qualities cannot be predicated of anything other than substances, not even of propositions and judgments
*** 6. Quality

** References
- [[https://www.youtube.com/watch?v=uovL2aX43Zk][Greg Sadler's Lectures on Categories, ch 1--4]]
- Andy Blunden,
  [[http://home.mira.net/~andy/works/aristotle.htm][Aristotle: The First Subject]]. ([[https://web.archive.org/web/20140213031524/http://home.mira.net/~andy/works/aristotle.htm][archived]])
- S.M. Cohen's
  [[http://faculty.washington.edu/smcohen/433/catlec.htm][Predication and Ontology: The Categories]].
- P. Bartha's
  [[http://faculty.arts.ubc.ca/pbartha/phil312/p312ho2.pdf][Philosophy 312 handout #2]].
- David Bradshaw's
  [[http://www.uky.edu/~jjord0/Aris.htm][Notes on Aristotle I]]
- Stanford Online Encyclopedia of Philosophy,
  [[http://plato.stanford.edu/entries/aristotle-categories/][Aristotle's Categories]].
- Riin Sirkel,
  [[http://ir.lib.uwo.ca/etd/62/][The Problem of Katholou (Universals) in Aristotle]].
  
